assets: /home/junsun/VLA/Temporal-VLA-newBaseline/starVLA-ours/LIBERO/libero/libero/./assets
bddl_files: /home/junsun/VLA/Temporal-VLA-newBaseline/starVLA-ours/LIBERO/libero/libero/./bddl_files
benchmark_root: /home/junsun/VLA/Temporal-VLA-newBaseline/starVLA-ours/LIBERO/libero/libero
datasets: /home/junsun/VLA/Temporal-VLA-newBaseline/starVLA-ours/LIBERO/libero/libero/../datasets
init_states: /home/junsun/VLA/Temporal-VLA-newBaseline/starVLA-ours/LIBERO/libero/libero/./init_files
